server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: LOCATION-SERVICE
          uri: lb://LOCATION-SERVICE
          predicates:
            - Path=/locations/**
          filters:
            - name: CircuitBreaker
              args:
                name: fallbackcmd
                fallbackuri: forward:/locationServiceFallBack

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream